"""
Phase 6: Migration Advisor
==========================
Reads the validation report JSON and the global DB of COMMON blocks.
For each block:
  - If CLEAN  → generates a Fortran 90 MODULE and USE instructions
  - If ISSUES → explains why it cannot be auto-migrated safely,
                and gives manual remediation advice per violation type

Usage:
    python migration_advisor.py <outputs_dir> <validation_report.json> [advice_output_dir]

Example:
    # For your test suite outputs:
    python migration_advisor.py outputs/ validation_report.json migration_advice/

    # For LAPACK:
    python migration_advisor.py lapack_outputs/ lapack_validation_report.json lapack_migration/
"""

import json
import os
import sys
from collections import defaultdict
from validator import load_all_jsons, build_global_db, validate


# ── Fortran 90 type string builder ───────────────────────────────────────────

def fortran90_type(var: dict) -> str:
    """Convert a variable dict to a Fortran 90 type declaration string."""
    t    = var["type"].upper()
    kind = var["kind"]
    dims = var.get("dimensions", [])

    if t == "CHARACTER":
        clen = var.get("char_len", 1)
        base = f"CHARACTER(LEN={clen})"
    elif t in ("REAL", "INTEGER", "COMPLEX", "LOGICAL"):
        base = f"{t}(KIND={kind})"
    else:
        base = t   # UNKNOWN or other

    if dims:
        dim_str = ", ".join(str(d) if d != -1 else ":" for d in dims)
        return f"{base}, DIMENSION({dim_str})"
    return base


def fortran90_module(block_name: str, variables: list[dict],
                     saved: bool) -> str:
    """Generate a complete Fortran 90 MODULE for a clean COMMON block."""
    mod_name = f"{block_name}_MOD"
    lines = []
    lines.append(f"MODULE {mod_name}")
    lines.append(f"  ! Auto-generated by Fortran COMMON Block Migration Advisor")
    lines.append(f"  ! Replaces: COMMON /{block_name}/")
    lines.append(f"  IMPLICIT NONE")
    if saved:
        lines.append(f"  SAVE")
    lines.append(f"")

    for var in variables:
        type_str = fortran90_type(var)
        vname    = var["name"]
        lines.append(f"  {type_str} :: {vname}")

    lines.append(f"")
    lines.append(f"END MODULE {mod_name}")
    return "\n".join(lines)


# ── USE instruction generator ─────────────────────────────────────────────────

def use_instructions(block_name: str, source_files: list[str]) -> str:
    """Generate the replacement instructions for each file."""
    mod_name = f"{block_name}_MOD"
    lines = []
    lines.append(f"  Replace in each file:")
    for f in source_files:
        lines.append(f"    {f}")
    lines.append(f"")
    lines.append(f"  Step 1: Remove the COMMON /{block_name}/ declaration")
    lines.append(f"  Step 2: Remove the variable type declarations that were")
    lines.append(f"          only needed for the COMMON block")
    lines.append(f"  Step 3: Add at the top of each subroutine/program:")
    lines.append(f"          USE {mod_name}")
    lines.append(f"  Step 4: Add the new module file {mod_name}.f90 to your build")
    return "\n".join(lines)


# ── Remediation advice per violation type ─────────────────────────────────────

def remediation_advice(issues: list[str], block_name: str,
                       declarations: list[dict]) -> list[str]:
    """Generate human-readable fix advice for each violation type."""
    advice = []

    has_size     = any("SIZE MISMATCH"      in i for i in issues)
    has_punning  = any("TYPE PUNNING"       in i for i in issues)
    has_kind     = any("KIND MISMATCH"      in i for i in issues)
    has_align    = any("ALIGNMENT"          in i for i in issues)
    has_save     = any("SAVE INCONSISTENCY" in i for i in issues)
    has_equiv    = any("EQUIVALENCE"        in i for i in issues)

    if has_size:
        # Find the largest declaration — that's the one to trust
        largest = max(declarations, key=lambda d: d["total_size"])
        advice.append(
            f"  [SIZE MISMATCH FIX]\n"
            f"  The authoritative declaration (largest) is in:\n"
            f"    {largest['source_file']} → {largest['total_size']} bytes\n"
            f"  Action: Audit all other declarations and align them to this size.\n"
            f"  Once sizes match, re-run the advisor to generate the MODULE."
        )

    if has_punning or has_kind:
        advice.append(
            f"  [TYPE PUNNING / KIND MISMATCH FIX]\n"
            f"  Variables at the same memory offset have incompatible types.\n"
            f"  This is intentional type-punning (reading bits as a different type)\n"
            f"  or an accidental bug.\n"
            f"  Action:\n"
            f"    - If intentional: use TRANSFER() intrinsic in Fortran 90\n"
            f"      instead of COMMON block aliasing.\n"
            f"      Example: i_val = TRANSFER(real_val, i_val)\n"
            f"    - If accidental: correct the type declarations so all files\n"
            f"      agree on the type at each offset."
        )

    if has_align:
        advice.append(
            f"  [ALIGNMENT FIX]\n"
            f"  One or more variables are not naturally aligned.\n"
            f"  Action: Reorder variables in the COMMON block so that larger\n"
            f"  types (REAL*8, COMPLEX*16) come first, followed by smaller ones.\n"
            f"  Rule: place variables in decreasing order of kind size."
        )

    if has_save:
        advice.append(
            f"  [SAVE INCONSISTENCY FIX]\n"
            f"  Some files declare SAVE, others do not.\n"
            f"  Action: Add SAVE to all declarations of /{block_name}/,\n"
            f"  or remove it from all. The MODULE approach (when violations\n"
            f"  are fixed) automatically handles persistence via module variables."
        )

    if has_equiv:
        advice.append(
            f"  [EQUIVALENCE FIX]\n"
            f"  EQUIVALENCE statements alias variables inside this COMMON block.\n"
            f"  This can silently shift variable offsets and is not portable.\n"
            f"  Action:\n"
            f"    - Replace array aliasing with explicit POINTER associations\n"
            f"      or pass the array as a subroutine argument.\n"
            f"    - After removing EQUIVALENCE, re-run the advisor."
        )

    return advice


# ── Report writer ─────────────────────────────────────────────────────────────

def write_migration_report(block_name: str, block_info: dict,
                           declarations: list[dict],
                           output_dir: str) -> str:
    """Write a .txt advice file + a .f90 module file (if clean)."""
    os.makedirs(output_dir, exist_ok=True)
    safe_name = block_name.replace("/", "_").replace("\\", "_")

    txt_path = os.path.join(output_dir, f"{safe_name}_advice.txt")
    lines = []

    lines.append("=" * 60)
    lines.append(f"  MIGRATION ADVICE: /{block_name}/")
    lines.append("=" * 60)
    lines.append(f"  Declared in {len(declarations)} file(s):")
    for d in declarations:
        lines.append(f"    - {d['source_file']}")
    lines.append("")

    if block_info["clean"]:
        # Pick the declaration with most variables (most complete)
        best = max(declarations, key=lambda d: len(d["variables"]))
        mod_code = fortran90_module(
            block_name, best["variables"], best["saved"]
        )
        mod_name = f"{block_name}_MOD"
        mod_file = os.path.join(output_dir, f"{mod_name}.f90")

        lines.append(f"  STATUS: ✓ CLEAN — Safe to auto-migrate\n")
        lines.append(f"  Generated MODULE file: {mod_name}.f90\n")
        lines.append(use_instructions(block_name, block_info["declared_in"]))
        lines.append("")
        lines.append("  ── Generated Module Code ──")
        lines.append("")
        for l in mod_code.splitlines():
            lines.append(f"  {l}")

        # Write the .f90 module file
        with open(mod_file, "w", encoding="utf-8") as f:
            f.write(mod_code + "\n")

    else:
        lines.append(f"  STATUS: ✗ UNSAFE — {len(block_info['issues'])} violation(s) found")
        lines.append(f"  Cannot auto-migrate until violations are fixed.\n")
        lines.append("  ── Violations ──")
        for issue in block_info["issues"]:
            for l in issue.splitlines():
                lines.append(f"  {l}")
        lines.append("")
        lines.append("  ── Remediation Steps ──")
        advice = remediation_advice(block_info["issues"], block_name, declarations)
        for a in advice:
            lines.append(a)
            lines.append("")

    lines.append("=" * 60)
    lines.append("")

    with open(txt_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return txt_path


# ── Console summary ───────────────────────────────────────────────────────────

def print_summary(report: dict, output_dir: str):
    s = report["summary"]
    clean  = s["total_blocks"] - s["blocks_with_issues"]
    unsafe = s["blocks_with_issues"]

    print("=" * 60)
    print("  MIGRATION ADVISOR SUMMARY")
    print("=" * 60)
    print(f"  Total COMMON blocks : {s['total_blocks']}")
    print(f"  Auto-migratable     : {clean}  (MODULE generated)")
    print(f"  Needs manual fix    : {unsafe}  (advice written)")
    print(f"  Output directory    : {output_dir}/")
    print("=" * 60)
    print()

    for block_name, info in report["blocks"].items():
        if info["clean"]:
            print(f"  ✓  /{block_name}/  →  {block_name}_MOD.f90 generated")
        else:
            print(f"  ✗  /{block_name}/  →  manual fix required "
                  f"({len(info['issues'])} issue(s))")
    print()


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    outputs_dir  = sys.argv[1] if len(sys.argv) > 1 else "outputs"
    report_path  = sys.argv[2] if len(sys.argv) > 2 else "validation_report.json"
    advice_dir   = sys.argv[3] if len(sys.argv) > 3 else "migration_advice"

    # Load report
    with open(report_path) as f:
        report = json.load(f)

    # Rebuild DB so we have full variable details
    records = load_all_jsons(outputs_dir)
    db      = build_global_db(records)

    # Generate advice for every block
    for block_name, block_info in report["blocks"].items():
        declarations = db.get(block_name, [])
        write_migration_report(block_name, block_info,
                               declarations, advice_dir)

    print_summary(report, advice_dir)
    print(f"[INFO] Detailed advice written to '{advice_dir}/'")


if __name__ == "__main__":
    main()